#!/usr/bin/python3
"""Make the Codex app's Chrome/browser connector work on this Mac.

Several gates stop the connector when Codex runs on API-key auth with no ChatGPT
account:

  gate 1  the browser runtime asks the Codex CLI for `getAuthStatus`, gets no
          token, and aborts browser discovery with
          "Codex auth token is unavailable";
  gate 2  `browser-service.mjs` inside the app bundle fetches
          chatgpt.com/backend-api/aura/identity and throws "User unavailable".
  gate 3  browser-service asks Statsig for a request-header policy and fails
          closed when no caller identity or remote policy is available.
  gate 4  26.928+ browser-service checks an admin-enforced origin policy and
          fails closed when `chatgpt.com` cannot verify it.

`--apply` fixes all of them, backing up every original first:

  * gates 2 through 4: patched in every live app-bundle and plugin-cache
    `browser-service.mjs` copy.
  * gate 2: the aura/identity lookup in the two app-bundle `browser-service.mjs`
    copies is replaced with a synthetic user object.
  * gate 3: the remote request-header feature gate is disabled.
  * gate 4: `getOriginPolicyDecision` is replaced with a local `null` decision.
    This bypasses the enterprise origin-policy source; persisted per-origin user
    permission checks still run separately.
  * gate 1: `cua_node/bin/node_repl` becomes a two-line wrapper that points
    CODEX_CLI_PATH at `codex-auth-shim.py`; the vendor binary is kept next to it
    as `node_repl-vendor`. The wrapper scope is deliberate: it changes the CLI
    only for node_repl, so the app's own app-server keeps using the real CLI.
  * gate 5: the Electron host's `canServeSession()` route check is rewritten
    inside `Resources/app.asar` so an in-app-browser backend parked on the
    placeholder session can be moved to the real conversation.

Because `~/.codex/config.toml` and the plugin cache are regenerated by the app
on every launch, patching them does not survive; the app bundle and the shim are
the durable patching points in app 26.911.61220 and later.

Editing a file inside `app.asar` invalidates three hashes that the packaged app
verifies at launch, and a mismatch is fatal (the app exits a few seconds after
it starts):

  1. each entry in the asar JSON header carries
     `integrity.hash`/`integrity.blocks` over that entry's bytes;
  2. `Info.plist` -> `ElectronAsarIntegrity` -> `Resources/app.asar` -> `hash`
     covers the asar JSON header itself;
  3. the Electron framework bakes a SHA-256 over the whole
     `ElectronAsarIntegrity` dictionary into the `__DATA_CONST,__asar_integrity`
     Mach-O section. Electron 41+ (`IsIntegrityDictionaryValid()`) refuses the
     dictionary when that digest no longer matches, which reports as
     `Failed to get integrity for validatable asar archive` rather than as a
     plain hash mismatch.

`patch_host_route()` therefore re-hashes the edited entry, rewrites the header
in place (SHA-256 hex is fixed width, so the header keeps its length and no file
offset moves), updates the `Info.plist` hash, and rewrites the framework digest
to match. Skipping any of these is what produced a boot loop on 2026-10-01;
`--check` reports `integrity-broken`, `header-integrity-broken` or
`dictionary-digest-stale` for those states.

Usage: patch-browser-connector.py [--check | --apply | --restore]
"""
import argparse
import glob
import hashlib
import json
import mmap
import os
import plistlib
import re
import shutil
import stat
import subprocess
import sys

APP = os.path.expanduser(os.environ.get("CHATGPT_APP", "/Applications/ChatGPT.app"))
RESOURCES = os.path.join(APP, "Contents/Resources")
INFO_PLIST = os.path.join(APP, "Contents/Info.plist")
ROLLBACK_DIR = os.path.expanduser(
    os.environ.get("CODEX_BROWSER_ROLLBACK_DIR", "~/.local/share/codex-rollback")
)
BACKUP_DIR = os.path.join(ROLLBACK_DIR, "appbundle-orig")
SHIM = os.path.join(ROLLBACK_DIR, "codex-auth-shim.py")
SHIM_MARKER = "codex-auth-shim-v2"
NODE_REPL = os.path.join(RESOURCES, "cua_node/bin/node_repl")
NODE_REPL_VENDOR = os.path.join(RESOURCES, "cua_node/bin/node_repl-vendor")
HOST_ASAR = os.path.join(RESOURCES, "app.asar")
HOST_ASAR_BACKUP = os.path.join(BACKUP_DIR, "app.asar")
INFO_PLIST_BACKUP = os.path.join(BACKUP_DIR, "Info.plist")
INFO_PLIST_ASAR_KEY = "Resources/app.asar"
FRAMEWORK_GLOB = os.path.join(
    APP,
    "Contents/Frameworks/Codex Framework.framework/Versions/*/Codex Framework",
)
FRAMEWORK_CURRENT = os.path.join(
    APP,
    "Contents/Frameworks/Codex Framework.framework/Versions/Current/Codex Framework",
)
FRAMEWORK_BACKUP = os.path.join(BACKUP_DIR, "Codex Framework")
# Mirrors IntegrityDictionaryDigestSlot in Electron's integrity_digest.mm.
INTEGRITY_SENTINEL = b"AGbevlPCksUGKNL8TSn7wGmJEuJsXb2A"
INTEGRITY_SLOT_SIZE = 32 + 1 + 1 + 32
HOST_MARKER = b"codex-browser-connector-host-route-v1"  # superseded, still detected
HOST_MARKER_V2 = b"cbc-host-route-v2"
HOST_START = b"canServeSession(e,t){let{sessionId:n}=t;"
HOST_V1_START = b"canServeSession(e,t){/* codex-browser-connector-host-route-v1 */"
# The region runs up to the next method of the same class, so the replacement
# can be sized from the file rather than from a hard-coded byte count.
HOST_REGION_END = b"async disposeBackendForSession(e){"
# v2 supersedes v1: v1 only relaxed the check that runs *after*
# backendStatesBySessionId matches, which is why it never fired. v2 answers the
# question the caller actually asks -- "is there a live route for this
# conversation?" -- and adopts a route parked under a `client-new-thread:`
# placeholder, re-keying it to the real conversation. It also logs the route
# table when it still cannot serve, so a failure is diagnosable in one run.
HOST_REPLACEMENT = (
    b"canServeSession(e,t){/* cbc-host-route-v2 */"
    b"if(this.ensureSessionRoute(e)===!0)return!0;"
    b"let{sessionId:n}=t,r=this.sessionRoutes.get(n),"
    b"p=String(n).startsWith(`client-new-thread:`),"
    b"A=x=>x!=null&&this.delegate?.isWindowAlive(x.windowId)===!0;"
    b"if(!A(r))for(let[c,q]of this.sessionRoutes)"
    b"if(String(c).startsWith(`client-new-thread:`)&&A(q)){n=c;r=q;p=!0;break}"
    b"if(!A(r))return ZJ().warning(`IAB_ROUTE_DIAG`,{safe:{c:e.conversationId,"
    b"b:t.sessionId,r:[...this.sessionRoutes.keys()].join(`|`)},sensitive:{}}),!1;"
    b"if(!p&&this.backendStatesBySessionId.get(n)!==t)return!1;"
    b"this.pendingLocalWorkSessionIds.delete(n),"
    b"this.localWorkCodexSessionIds.set(n,e.conversationId),"
    b"this.moveBackendSession(n,e.conversationId),"
    b"this.captureSessionRouteForWindow({"
    b"browserConversationId:r.browserConversationId,"
    b"disposeAfterSessionActivity:r.disposeAfterSessionActivity,"
    b"ownerWebContentsId:r.ownerWebContentsId,"
    b"sessionId:e.conversationId,windowId:r.windowId}),"
    b"this.sessionRoutes.delete(n);"
    b"return this.ensureSessionRoute(e)}"
)

APP_BUNDLE_TARGETS = [
    (
        os.path.join(
            RESOURCES,
            "cua_node/lib/node_modules/@oai/browser-desktop/scripts/browser-service.mjs",
        ),
        "browser-desktop.browser-service.mjs",
    ),
    (
        os.path.join(
            RESOURCES,
            "cua_node/lib/node_modules/@oai/cua/dist/lib/js/oai_js_browser/dist/skill/scripts/browser-service.mjs",
        ),
        "cua-skill.browser-service.mjs",
    ),
]

# The runtime's NODE_REPL_TRUSTED_SERVICES points at the plugin-cache copy of the
# same service, so it carries gate 2 too. The cache path is version-keyed, hence
# the glob: cover every version directory that exists.
PLUGIN_CACHE_GLOB = os.path.expanduser(
    "~/.codex/plugins/cache/openai-bundled/*/*/scripts/browser-service.mjs"
)


def mjs_targets():
    targets = [
        (path, os.path.join(BACKUP_DIR, name)) for path, name in APP_BUNDLE_TARGETS
    ]
    for path in sorted(glob.glob(PLUGIN_CACHE_GLOB)):
        if "/latest/" in path:  # symlink to a version directory already covered
            continue
        plugin = path.split("/openai-bundled/")[1].split("/")[0]
        version = path.split("/scripts/")[0].rsplit("/", 1)[1]
        targets.append(
            (
                path,
                os.path.join(BACKUP_DIR, "cache-%s-%s.browser-service.mjs" % (plugin, version)),
            )
        )
    return targets

MARKER = "codex-browser-connector-patch"
REQUEST_HEADER_MARKER = "codex-browser-connector-request-header-patch"
POLICY_MARKER = "codex-browser-connector-policy-local-v1"
WRAPPER_MARKER = "codex-browser-connector-wrapper-v3"
PATCH_RE = re.compile(
    r'if\((?P<c>[A-Za-z_$][\w$]*)!=null\)return (?P=c);'
    r'let (?P<r>[A-Za-z_$][\w$]*)=await [A-Za-z_$][\w$]*\.fetch\('
    r'"https://chatgpt\.com/backend-api/aura/identity".*?'
    r'throw new Error\("User unavailable"\);return (?P=c)=[A-Za-z_$][\w$]*,(?P=c)'
)
REQUEST_HEADER_RE = re.compile(
    r'async function (?P<f>[A-Za-z_$][\w$]*)\(\)\{'
    r'if\((?P<c>[A-Za-z_$][\w$]*)==null\)throw new Error\('
    r'"Browser request-header policy requires caller identity\."\);'
    r'return await (?P=c),[A-Za-z_$][\w$]*\('
    r'"codex_browser_use_agent_request_header"\)\}'
)
POLICY_RE = re.compile(
    r'async getOriginPolicyDecision\('
    r'(?P<origin>[A-Za-z_$][\w$]*),(?P<kind>[A-Za-z_$][\w$]*)\)\{'
    r'.*?\}(?=async getFullCdpPermission)'
)


def replacement(match):
    """Keep the file's own cache-variable name so the patched module still parses."""
    cache = match.group("c")
    return 'if(%s!=null)return %s;let r={object:"user",id:"%s"};%s=r;return r' % (
        cache,
        cache,
        MARKER,
        cache,
    )


def request_header_replacement(match):
    """Disable the remote feature gate; local use does not need its request header."""
    return "async function %s(){/* %s */return!1}" % (
        match.group("f"),
        REQUEST_HEADER_MARKER,
    )


def policy_replacement(match):
    """Use the local browser policy instead of the enterprise source."""
    return "async getOriginPolicyDecision(%s,%s){/* %s */return null}" % (
        match.group("origin"),
        match.group("kind"),
        POLICY_MARKER,
    )


WRAPPER = """#!/bin/sh
# %s: give node_repl a CLI that answers getAuthStatus.
CODEX_CLI_PATH="%s"
export CODEX_CLI_PATH
exec "$(dirname "$0")/node_repl-vendor" "$@"
""" % (WRAPPER_MARKER, SHIM)


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def is_text_file(path):
    try:
        with open(path, "rb") as fh:
            return b"\0" not in fh.read(4096)
    except OSError:
        return False


def mjs_status(path):
    if not os.path.exists(path):
        return "missing"
    body = open(path, encoding="utf-8", errors="replace").read()
    aura_patched = MARKER in body
    header_patched = REQUEST_HEADER_MARKER in body
    policy_patched = POLICY_MARKER in body
    if aura_patched and header_patched and policy_patched:
        return "patched"
    if aura_patched or header_patched or policy_patched:
        return "partial"
    if "User unavailable" in body:
        return "unpatched"
    return "unknown (no aura/identity check found)"


def node_repl_status():
    if not os.path.exists(NODE_REPL):
        return "missing"
    if is_text_file(NODE_REPL):
        body = open(NODE_REPL, encoding="utf-8", errors="replace").read()
        if (
            SHIM in body
            and WRAPPER_MARKER in body
            and os.path.exists(NODE_REPL_VENDOR)
        ):
            return "patched"
        return "unknown wrapper"
    return "unpatched"


def shim_status():
    if not os.path.exists(SHIM):
        return "missing"
    body = open(SHIM, encoding="utf-8", errors="replace").read()
    return "patched" if SHIM_MARKER in body else "outdated"


def clone_file(src, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    try:
        subprocess.run(
            ["cp", "-c", src, dst],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except Exception:
        shutil.copy2(src, dst)


# --- asar integrity ---------------------------------------------------------
#
# Electron refuses to load an entry whose bytes no longer match the SHA-256 the
# asar JSON header recorded for it, and refuses the archive outright when the
# header itself no longer matches Info.plist. Editing `canServeSession()` inside
# app.asar therefore has to rewrite both, or the app exits seconds after launch
# with "ASAR Integrity Violation: got a hash mismatch".


def asar_header_span(mm):
    """Return (json_start, json_size) for a mapped asar file."""
    json_start = mm.find(b'{"files":')
    if json_start < 4:
        raise ValueError("no asar JSON header found")
    json_size = int.from_bytes(mm[json_start - 4 : json_start], "little")
    if json_size <= 0 or json_start + json_size > len(mm):
        raise ValueError("asar JSON header is out of range")
    return json_start, json_size


def asar_entry_at(header, content_offset):
    """Return the header node that owns content_offset, or None."""
    stack = [header]
    while stack:
        node = stack.pop()
        for value in node.get("files", {}).values():
            if "files" in value:
                stack.append(value)
            elif "offset" in value:
                start = int(value["offset"])
                if start <= content_offset < start + value["size"]:
                    return value
    return None


def hash_region(mm, offset, size, block_size=None):
    """SHA-256 of a mapped region, plus per-block hashes when block_size is set."""
    digest = hashlib.sha256()
    mm.seek(offset)
    remaining = size
    while remaining > 0:
        chunk = mm.read(min(1 << 20, remaining))
        if not chunk:
            raise ValueError("short read at %d" % offset)
        digest.update(chunk)
        remaining -= len(chunk)
    blocks = None
    if block_size:
        blocks = []
        for start in range(offset, offset + size, block_size):
            block = hashlib.sha256()
            mm.seek(start)
            remaining = min(block_size, offset + size - start)
            while remaining > 0:
                chunk = mm.read(min(1 << 20, remaining))
                if not chunk:
                    raise ValueError("short read at %d" % start)
                block.update(chunk)
                remaining -= len(chunk)
            blocks.append(block.hexdigest())
    return digest.hexdigest(), blocks


def info_plist_asar_hash():
    with open(INFO_PLIST, "rb") as fh:
        plist = plistlib.load(fh)
    return plist["ElectronAsarIntegrity"][INFO_PLIST_ASAR_KEY]["hash"]


def set_info_plist_asar_hash(new_hash):
    """Point ElectronAsarIntegrity at a rewritten header, touching nothing else."""
    with open(INFO_PLIST, "rb") as fh:
        body = fh.read()
    old_hash = info_plist_asar_hash()
    if old_hash == new_hash:
        return
    if len(new_hash) == len(old_hash) and body.count(old_hash.encode()) == 1:
        body = body.replace(old_hash.encode(), new_hash.encode())
    else:
        # Not a unique literal: fall back to a structural rewrite.
        plist = plistlib.loads(body)
        plist["ElectronAsarIntegrity"][INFO_PLIST_ASAR_KEY]["hash"] = new_hash
        body = plistlib.dumps(plist, fmt=plistlib.FMT_XML)
    tmp = INFO_PLIST + ".tmp-patch"
    with open(tmp, "wb") as fh:
        fh.write(body)
    with open(tmp, "rb") as fh:
        plistlib.load(fh)  # never install a plist we cannot parse back
    shutil.copymode(INFO_PLIST, tmp)
    os.replace(tmp, INFO_PLIST)
    print("updated ElectronAsarIntegrity hash in %s" % INFO_PLIST)


def framework_binary():
    """Path of the Electron framework that carries the packaged digest."""
    if os.path.exists(FRAMEWORK_CURRENT):
        return FRAMEWORK_CURRENT
    matches = sorted(glob.glob(FRAMEWORK_GLOB))
    return matches[-1] if matches else None


def integrity_dictionary_digest(dictionary):
    """Reproduce Electron's IsIntegrityDictionaryValid() digest.

    integrity_digest.mm walks the dictionary's keys in literal sort order and
    absorbs the UTF-8 bytes of the key, the algorithm and the hash of each
    entry, with no separators or length prefixes.
    """
    hasher = hashlib.sha256()
    for key in sorted(dictionary):
        entry = dictionary[key]
        hasher.update(key.encode("utf-8"))
        hasher.update(str(entry.get("algorithm", "")).encode("utf-8"))
        hasher.update(str(entry.get("hash", "")).encode("utf-8"))
    return hasher.digest()


def current_integrity_digest():
    with open(INFO_PLIST, "rb") as fh:
        plist = plistlib.load(fh)
    return integrity_dictionary_digest(plist["ElectronAsarIntegrity"])


def find_integrity_slots(path):
    """Locate the __asar_integrity digest slots WITHOUT mapping the file.

    The framework must never be mmapped once its signature is stale: macOS
    kills any process that maps one of its pages ("CODESIGNING, Code 2 Invalid
    Page"). Plain read()/write() through a file descriptor is safe.

    Returns [(file_offset, used, version, digest_bytes)].
    """
    slots = []
    keep = INTEGRITY_SLOT_SIZE - 1
    with open(path, "rb") as fh:
        carry = b""
        buf_start = 0
        while True:
            chunk = fh.read(1 << 20)
            if not chunk and not carry:
                break
            buf = carry + chunk
            at = 0
            while True:
                at = buf.find(INTEGRITY_SENTINEL, at)
                if at < 0:
                    break
                if at + INTEGRITY_SLOT_SIZE <= len(buf):
                    slot = buf[at : at + INTEGRITY_SLOT_SIZE]
                    slots.append((buf_start + at, slot[32], slot[33], slot[34:66]))
                at += 1
            carry = buf[-keep:]
            buf_start += len(buf) - len(carry)
            if not chunk:
                break
    return slots


def framework_integrity_status():
    """ok | stale | missing | unknown.

    `stale` is the state that makes Electron 41+ log
    "Failed to get integrity for validatable asar archive" and exit.
    """
    path = framework_binary()
    if path is None or not os.path.exists(path):
        return "missing"
    try:
        expected = current_integrity_digest()
        slots = find_integrity_slots(path)
        if not slots:
            return "missing"
        stale = False
        for _offset, used, version, digest in slots:
            if used == 0:  # used == false: Electron fails open
                continue
            if version != 1:
                return "unknown"
            if digest != expected:
                stale = True
        return "stale" if stale else "ok"
    except Exception:
        return "unknown"


def patch_framework_integrity():
    path = framework_binary()
    if path is None:
        sys.exit("could not find the Codex Framework binary under %s" % APP)
    if not os.path.exists(FRAMEWORK_BACKUP):
        clone_file(path, FRAMEWORK_BACKUP)
        print(
            "backed up -> %s (%s)"
            % (FRAMEWORK_BACKUP, sha256(FRAMEWORK_BACKUP)[:16])
        )
    expected = current_integrity_digest()
    slots = find_integrity_slots(path)
    if not slots:
        sys.exit("no __asar_integrity digest slot found in %s" % path)
    changed = 0
    with open(path, "r+b") as fh:
        for offset, used, version, digest in slots:
            if used == 0:
                continue
            if version != 1:
                sys.exit(
                    "unsupported __asar_integrity digest version %d in %s"
                    % (version, path)
                )
            if digest != expected:
                fh.seek(offset + 34)
                fh.write(expected)
                changed += 1
        fh.flush()
        os.fsync(fh.fileno())
    print(
        "updated asar integrity dictionary digest in %s (%d slot(s))"
        % (path, changed)
    )
    return changed


def rehash_asar_entry(path, patched_offset):
    """Re-hash the asar entry covering patched_offset and rewrite the header.

    Returns the SHA-256 of the new header, which is what Info.plist must carry,
    or None when the offset does not fall inside a known entry.
    """
    with open(path, "r+b") as fh:
        with mmap.mmap(fh.fileno(), 0) as mm:
            json_start, json_size = asar_header_span(mm)
            base = json_start + json_size
            header = json.loads(mm[json_start : json_start + json_size])
            entry = asar_entry_at(header, patched_offset - base)
            if entry is None or "integrity" not in entry:
                return None
            digest, blocks = hash_region(
                mm,
                base + int(entry["offset"]),
                entry["size"],
                entry["integrity"].get("blockSize"),
            )
            entry["integrity"]["hash"] = digest
            if blocks is not None:
                entry["integrity"]["blocks"] = blocks
            new_header = json.dumps(
                header, separators=(",", ":"), ensure_ascii=False
            ).encode("utf-8")
            if len(new_header) != json_size:
                raise ValueError(
                    "asar header length changed (%d -> %d); refusing to rewrite"
                    % (json_size, len(new_header))
                )
            mm.seek(json_start)
            mm.write(new_header)
            mm.flush()
            return hashlib.sha256(new_header).hexdigest()


def host_route_status():
    if not os.path.exists(HOST_ASAR):
        return "missing"
    try:
        with open(HOST_ASAR, "rb") as fh:
            with mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ) as mm:
                if mm.find(HOST_MARKER_V2) >= 0:
                    marker, current = mm.find(HOST_MARKER_V2), True
                elif mm.find(HOST_MARKER) >= 0:
                    marker, current = mm.find(HOST_MARKER), False
                elif mm.find(HOST_START) >= 0:
                    return "unpatched"
                else:
                    return "unknown"
                json_start, json_size = asar_header_span(mm)
                base = json_start + json_size
                header = json.loads(mm[json_start : json_start + json_size])
                entry = asar_entry_at(header, marker - base)
                if entry is None or "integrity" not in entry:
                    return "unknown"
                digest, blocks = hash_region(
                    mm,
                    base + int(entry["offset"]),
                    entry["size"],
                    entry["integrity"].get("blockSize"),
                )
                if digest != entry["integrity"]["hash"]:
                    return "integrity-broken"
                if blocks is not None and blocks != entry["integrity"].get("blocks"):
                    return "integrity-broken"
                header_hash = hashlib.sha256(
                    mm[json_start : json_start + json_size]
                ).hexdigest()
                try:
                    expected = info_plist_asar_hash()
                except Exception:
                    return "unknown"
                if header_hash != expected:
                    return "header-integrity-broken"
                if framework_integrity_status() == "stale":
                    return "dictionary-digest-stale"
                return "patched" if current else "outdated"
    except Exception:
        return "unknown"


def repair_host_integrity():
    """Re-derive all three guard hashes for an already-spliced host route.

    Reachable after a partial or older patch: the route bytes are in the asar
    but one of the integrity guards describes the previous contents, which is
    exactly the state that stops the app booting.
    """
    with open(HOST_ASAR, "rb") as fh:
        with mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ) as mm:
            marker = mm.find(HOST_MARKER_V2)
            if marker < 0:
                marker = mm.find(HOST_MARKER)
    if marker < 0:
        sys.exit("no host route marker in %s; restore instead" % HOST_ASAR)
    new_header_hash = rehash_asar_entry(HOST_ASAR, marker)
    if new_header_hash is None:
        sys.exit("could not find the asar entry covering the host route")
    set_info_plist_asar_hash(new_header_hash)
    patch_framework_integrity()
    print(
        "repaired host route integrity: %s (header sha256 %s)"
        % (HOST_ASAR, new_header_hash[:16])
    )


def patch_host_route():
    status = host_route_status()
    if status == "patched":
        print("already patched: %s" % HOST_ASAR)
        return
    if status in (
        "integrity-broken",
        "header-integrity-broken",
        "dictionary-digest-stale",
    ):
        repair_host_integrity()
        return
    if status not in ("unpatched", "outdated"):
        sys.exit(
            "could not patch %s: expected an unpatched or v1 canServeSession "
            "route check, found %s" % (HOST_ASAR, status)
        )
    if not os.path.exists(HOST_ASAR_BACKUP):
        clone_file(HOST_ASAR, HOST_ASAR_BACKUP)
        print(
            "backed up -> %s (%s)"
            % (HOST_ASAR_BACKUP, sha256(HOST_ASAR_BACKUP)[:16])
        )
    if not os.path.exists(INFO_PLIST_BACKUP):
        os.makedirs(BACKUP_DIR, exist_ok=True)
        shutil.copy2(INFO_PLIST, INFO_PLIST_BACKUP)
        print("backed up -> %s" % INFO_PLIST_BACKUP)
    tmp = HOST_ASAR + ".tmp-patch"
    with open(HOST_ASAR, "rb") as src:
        with mmap.mmap(src.fileno(), 0, access=mmap.ACCESS_READ) as mm:
            start = mm.find(HOST_START)
            if start < 0:  # already carries the superseded v1 splice
                start = mm.find(HOST_V1_START)
            end = mm.find(HOST_REGION_END, start if start >= 0 else 0)
            if start < 0 or end < start:
                sys.exit("could not locate the host browser route method")
            old_end = end
            old_size = old_end - start
            if len(HOST_REPLACEMENT) > old_size:
                sys.exit(
                    "host route replacement is %d bytes too large"
                    % (len(HOST_REPLACEMENT) - old_size)
                )
            replacement = HOST_REPLACEMENT + b" " * (
                old_size - len(HOST_REPLACEMENT)
            )
            with open(tmp, "wb") as out:
                mm.seek(0)
                remaining = start
                while remaining > 0:
                    chunk = mm.read(min(1 << 20, remaining))
                    if not chunk:
                        break
                    out.write(chunk)
                    remaining -= len(chunk)
                out.write(replacement)
                mm.seek(old_end)
                while True:
                    chunk = mm.read(1 << 20)
                    if not chunk:
                        break
                    out.write(chunk)
    shutil.copymode(HOST_ASAR, tmp)
    new_header_hash = rehash_asar_entry(tmp, start)
    if new_header_hash is None:
        os.remove(tmp)
        sys.exit("could not find the asar entry covering the patched bytes")
    set_info_plist_asar_hash(new_header_hash)
    patch_framework_integrity()
    os.replace(tmp, HOST_ASAR)
    print(
        "patched host browser route: %s (header sha256 %s)"
        % (HOST_ASAR, new_header_hash[:16])
    )


def check():
    print("app version: %s" % app_version())
    ok = True
    for path, _backup in mjs_targets():
        status = mjs_status(path)
        ok = ok and status == "patched"
        print("%-9s %s" % (status, path))
    status = node_repl_status()
    ok = ok and status == "patched"
    print("%-9s %s" % (status, NODE_REPL))
    status = shim_status()
    ok = ok and status == "patched"
    print("%-9s %s" % (status, SHIM))
    status = host_route_status()
    ok = ok and status == "patched"
    print("%-9s %s" % (status, HOST_ASAR))
    return 0 if ok else 1


def app_version():
    try:
        out = subprocess.run(
            ["defaults", "read", os.path.join(APP, "Contents/Info"), "CFBundleShortVersionString"],
            capture_output=True, text=True, check=True,
        )
        return out.stdout.strip()
    except Exception:
        return "unknown"


def apply_patch():
    os.makedirs(BACKUP_DIR, exist_ok=True)
    if shim_status() != "patched":
        sys.exit("shim missing or outdated at %s; run deploy.sh first" % SHIM)
    for path, backup in mjs_targets():
        if not os.path.exists(path):
            print("skip (not present): %s" % path)
            continue
        status = mjs_status(path)
        if status == "patched":
            print("already patched: %s" % path)
            continue
        if not os.path.exists(backup):
            shutil.copy2(path, backup)
            print("backed up -> %s (%s)" % (backup, sha256(backup)[:16]))
        body = open(path, encoding="utf-8").read()
        new_body = body
        if MARKER not in new_body:
            new_body, count = PATCH_RE.subn(replacement, new_body)
            if count != 1:
                sys.exit(
                    "could not patch %s: expected 1 aura/identity check, found %d "
                    "(the app changed; re-derive the snippet from the new file)"
                    % (path, count)
                )
        if REQUEST_HEADER_MARKER not in new_body:
            new_body, count = REQUEST_HEADER_RE.subn(
                request_header_replacement, new_body
            )
            if count != 1:
                sys.exit(
                    "could not patch %s: expected 1 request-header check, found %d "
                    "(the app changed; re-derive the snippet from the new file)"
                    % (path, count)
                )
        if POLICY_MARKER not in new_body:
            new_body, count = POLICY_RE.subn(policy_replacement, new_body)
            if count != 1:
                sys.exit(
                    "could not patch %s: expected 1 origin-policy check, found %d "
                    "(the app changed; re-derive the snippet from the new file)"
                    % (path, count)
                )
        tmp = path + ".tmp-patch"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(new_body)
        shutil.copymode(path, tmp)
        os.replace(tmp, path)
        print("patched browser-service gates: %s" % path)

    if node_repl_status() == "patched":
        print("already patched: %s" % NODE_REPL)
    else:
        if not is_text_file(NODE_REPL):
            shutil.copy2(NODE_REPL, NODE_REPL_VENDOR)
            print("kept vendor binary -> %s" % NODE_REPL_VENDOR)
        elif not os.path.exists(NODE_REPL_VENDOR):
            sys.exit(
                "node_repl is a wrapper but %s is missing; restore or reinstall "
                "the app before applying" % NODE_REPL_VENDOR
            )
        with open(NODE_REPL, "w") as fh:
            fh.write(WRAPPER)
        os.chmod(NODE_REPL, 0o755)
        print("patched gate 1: %s -> %s" % (NODE_REPL, SHIM))
    patch_host_route()
    return check()


def restore_host():
    """Restore only the Electron host asar and the hash Info.plist carries for it.

    Leaves `browser-service.mjs` and `node_repl` patched: those live outside the
    asar and are not integrity-checked, so gates 2-4 keep working. Use this when
    the host route patch alone misbehaves.
    """
    if os.path.exists(HOST_ASAR_BACKUP):
        tmp = HOST_ASAR + ".tmp-restore"
        clone_file(HOST_ASAR_BACKUP, tmp)
        shutil.copymode(HOST_ASAR, tmp)
        os.replace(tmp, HOST_ASAR)
        print("restored %s" % HOST_ASAR)
    else:
        print("no host route backup for %s; left as is" % HOST_ASAR)
    # The asar and the Info.plist hash it is checked against must go back together.
    if os.path.exists(INFO_PLIST_BACKUP):
        tmp = INFO_PLIST + ".tmp-restore"
        shutil.copy2(INFO_PLIST_BACKUP, tmp)
        shutil.copymode(INFO_PLIST, tmp)
        os.replace(tmp, INFO_PLIST)
        print("restored %s" % INFO_PLIST)
    else:
        print("no Info.plist backup for %s; left as is" % INFO_PLIST)
    # ... and so must the framework digest that guards the Info.plist dictionary.
    path = framework_binary()
    if path is not None and os.path.exists(FRAMEWORK_BACKUP):
        tmp = path + ".tmp-restore"
        clone_file(FRAMEWORK_BACKUP, tmp)
        shutil.copymode(path, tmp)
        os.replace(tmp, path)
        print("restored %s" % path)
    elif not os.path.exists(FRAMEWORK_BACKUP):
        print("no framework backup for %s; left as is" % (path or "framework"))


def restore():
    restore_host()
    for path, backup in mjs_targets():
        if os.path.exists(backup):
            shutil.copy2(backup, path)
            print("restored %s" % path)
        else:
            print("no backup for %s; left as is" % path)
    if os.path.exists(NODE_REPL_VENDOR):
        try:
            os.chmod(NODE_REPL, 0o755)
        except OSError:
            pass
        os.remove(NODE_REPL)
        os.rename(NODE_REPL_VENDOR, NODE_REPL)
        print("restored vendor node_repl")
    print("restored; relaunch the app to load the unpatched bundle")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="report patch state (default)")
    group.add_argument("--apply", action="store_true", help="back up and patch")
    group.add_argument("--restore", action="store_true", help="put the originals back")
    group.add_argument(
        "--restore-host",
        action="store_true",
        help="restore only the host app.asar and its Info.plist integrity hash",
    )
    args = parser.parse_args()
    if args.apply:
        sys.exit(apply_patch())
    if args.restore:
        sys.exit(restore())
    if args.restore_host:
        sys.exit(restore_host())
    sys.exit(check())


if __name__ == "__main__":
    main()
