#!/usr/bin/python3
"""Make the Codex app's Chrome/browser connector work on this Mac.

Several gates stop the connector when Codex runs on API-key auth with no ChatGPT
account:

  gate 1  the browser runtime asks the Codex CLI for `getAuthStatus`, gets no
          token, and aborts browser discovery with
          "Codex auth token is unavailable";
  gate 2  `browser-service.mjs` inside the app bundle fetches
          chatgpt.com/backend-api/aura/identity and throws "User unavailable".
  gate 3  browser-service asks Statsig for a request-header policy and fails
          closed when no caller identity or remote policy is available.
  gate 4  26.928+ browser-service checks an admin-enforced origin policy and
          fails closed when `chatgpt.com` cannot verify it.

`--apply` fixes all of them, backing up every original first:

  * gates 2 through 4: patched in every live app-bundle and plugin-cache
    `browser-service.mjs` copy.
  * gate 2: the aura/identity lookup in the two app-bundle `browser-service.mjs`
    copies is replaced with a synthetic user object.
  * gate 3: the remote request-header feature gate is disabled.
  * gate 4: `getOriginPolicyDecision` is replaced with a local `null` decision.
    This bypasses the enterprise origin-policy source; persisted per-origin user
    permission checks still run separately.
  * gate 1: `cua_node/bin/node_repl` becomes a two-line wrapper that points
    CODEX_CLI_PATH at `codex-auth-shim.py`; the vendor binary is kept next to it
    as `node_repl-vendor`. The wrapper scope is deliberate: it changes the CLI
    only for node_repl, so the app's own app-server keeps using the real CLI.

Because `~/.codex/config.toml` and the plugin cache are regenerated by the app
on every launch, patching them does not survive; the app bundle and the shim are
the durable patching points in app 26.911.61220 and later.

Usage: patch-browser-connector.py [--check | --apply | --restore]
"""
import argparse
import glob
import hashlib
import os
import re
import shlex
import shutil
import stat
import subprocess
import sys

APP = os.environ.get("CHATGPT_APP", "/Applications/ChatGPT.app")
RESOURCES = os.path.join(APP, "Contents/Resources")
ROLLBACK_DIR = os.path.expanduser(
    os.environ.get("CODEX_BROWSER_ROLLBACK_DIR", "~/.local/share/codex-rollback")
)
BACKUP_DIR = os.path.join(ROLLBACK_DIR, "appbundle-orig")
SHIM = os.path.join(ROLLBACK_DIR, "codex-auth-shim.py")
NODE_REPL = os.path.join(RESOURCES, "cua_node/bin/node_repl")
NODE_REPL_VENDOR = os.path.join(RESOURCES, "cua_node/bin/node_repl-vendor")
CODEX_HOME = os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex"))

APP_BUNDLE_TARGETS = [
    (
        os.path.join(
            RESOURCES,
            "cua_node/lib/node_modules/@oai/browser-desktop/scripts/browser-service.mjs",
        ),
        "browser-desktop.browser-service.mjs",
    ),
    (
        os.path.join(
            RESOURCES,
            "cua_node/lib/node_modules/@oai/cua/dist/lib/js/oai_js_browser/dist/skill/scripts/browser-service.mjs",
        ),
        "cua-skill.browser-service.mjs",
    ),
]

# The runtime's NODE_REPL_TRUSTED_SERVICES points at the plugin-cache copy of the
# same service, so it carries gate 2 too. The cache path is version-keyed, hence
# the glob: cover every version directory that exists.
PLUGIN_CACHE_GLOB = os.path.join(
    CODEX_HOME, "plugins/cache/openai-bundled/*/*/scripts/browser-service.mjs"
)


def mjs_targets():
    targets = [
        (path, os.path.join(BACKUP_DIR, name)) for path, name in APP_BUNDLE_TARGETS
    ]
    for path in sorted(glob.glob(PLUGIN_CACHE_GLOB)):
        if "/latest/" in path:  # symlink to a version directory already covered
            continue
        plugin = path.split("/openai-bundled/")[1].split("/")[0]
        version = path.split("/scripts/")[0].rsplit("/", 1)[1]
        targets.append(
            (
                path,
                os.path.join(BACKUP_DIR, "cache-%s-%s.browser-service.mjs" % (plugin, version)),
            )
        )
    return targets

MARKER = "codex-browser-connector-patch"
REQUEST_HEADER_MARKER = "codex-browser-connector-request-header-patch"
POLICY_MARKER = "codex-browser-connector-policy-local-v1"
WRAPPER_MARKER = "codex-browser-connector-wrapper-v3"
PATCH_RE = re.compile(
    r'if\((?P<c>[A-Za-z_$][\w$]*)!=null\)return (?P=c);'
    r'let (?P<r>[A-Za-z_$][\w$]*)=await [A-Za-z_$][\w$]*\.fetch\('
    r'"https://chatgpt\.com/backend-api/aura/identity".*?'
    r'throw new Error\("User unavailable"\);return (?P=c)=[A-Za-z_$][\w$]*,(?P=c)'
)
REQUEST_HEADER_RE = re.compile(
    r'async function (?P<f>[A-Za-z_$][\w$]*)\(\)\{'
    r'if\((?P<c>[A-Za-z_$][\w$]*)==null\)throw new Error\('
    r'"Browser request-header policy requires caller identity\."\);'
    r'return await (?P=c),[A-Za-z_$][\w$]*\('
    r'"codex_browser_use_agent_request_header"\)\}'
)
POLICY_RE = re.compile(
    r'async getOriginPolicyDecision\('
    r'(?P<origin>[A-Za-z_$][\w$]*),(?P<kind>[A-Za-z_$][\w$]*)\)\{'
    r'.*?\}(?=async getFullCdpPermission)'
)


def replacement(match):
    """Keep the file's own cache-variable name so the patched module still parses."""
    cache = match.group("c")
    return 'if(%s!=null)return %s;let r={object:"user",id:"%s"};%s=r;return r' % (
        cache,
        cache,
        MARKER,
        cache,
    )


def request_header_replacement(match):
    """Disable the remote feature gate; local use does not need its request header."""
    return "async function %s(){/* %s */return!1}" % (
        match.group("f"),
        REQUEST_HEADER_MARKER,
    )


def policy_replacement(match):
    """Use the local browser policy instead of the enterprise source."""
    return "async getOriginPolicyDecision(%s,%s){/* %s */return null}" % (
        match.group("origin"),
        match.group("kind"),
        POLICY_MARKER,
    )


WRAPPER = """#!/bin/sh
# %s: give node_repl a CLI that answers getAuthStatus.
CODEX_CLI_PATH="%s"
export CODEX_CLI_PATH
exec "$(dirname "$0")/node_repl-vendor" "$@"
""" % (WRAPPER_MARKER, shlex.quote(SHIM))


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def is_text_file(path):
    try:
        with open(path, "rb") as fh:
            return b"\0" not in fh.read(4096)
    except OSError:
        return False


def mjs_status(path):
    if not os.path.exists(path):
        return "missing"
    body = open(path, encoding="utf-8", errors="replace").read()
    aura_patched = MARKER in body
    header_patched = REQUEST_HEADER_MARKER in body
    policy_patched = POLICY_MARKER in body
    if aura_patched and header_patched and policy_patched:
        return "patched"
    if aura_patched or header_patched or policy_patched:
        return "partial"
    if "User unavailable" in body:
        return "unpatched"
    return "unknown (no aura/identity check found)"


def node_repl_status():
    if not os.path.exists(NODE_REPL):
        return "missing"
    if is_text_file(NODE_REPL):
        body = open(NODE_REPL, encoding="utf-8", errors="replace").read()
        if (
            SHIM in body
            and WRAPPER_MARKER in body
            and os.path.exists(NODE_REPL_VENDOR)
        ):
            return "patched"
        return "unknown wrapper"
    return "unpatched"


def check():
    print("app version: %s" % app_version())
    ok = True
    for path, _backup in mjs_targets():
        status = mjs_status(path)
        ok = ok and status == "patched"
        print("%-9s %s" % (status, path))
    status = node_repl_status()
    ok = ok and status == "patched"
    print("%-9s %s" % (status, NODE_REPL))
    print("shim: %s" % ("present" if os.path.exists(SHIM) else "missing"))
    return 0 if ok else 1


def app_version():
    try:
        out = subprocess.run(
            ["defaults", "read", os.path.join(APP, "Contents/Info"), "CFBundleShortVersionString"],
            capture_output=True, text=True, check=True,
        )
        return out.stdout.strip()
    except Exception:
        return "unknown"


def apply_patch():
    os.makedirs(BACKUP_DIR, exist_ok=True)
    if not os.path.exists(SHIM):
        sys.exit("shim missing at %s; run deploy.sh first" % SHIM)
    for path, backup in mjs_targets():
        if not os.path.exists(path):
            print("skip (not present): %s" % path)
            continue
        status = mjs_status(path)
        if status == "patched":
            print("already patched: %s" % path)
            continue
        if not os.path.exists(backup):
            shutil.copy2(path, backup)
            print("backed up -> %s (%s)" % (backup, sha256(backup)[:16]))
        body = open(path, encoding="utf-8").read()
        new_body = body
        if MARKER not in new_body:
            new_body, count = PATCH_RE.subn(replacement, new_body)
            if count != 1:
                sys.exit(
                    "could not patch %s: expected 1 aura/identity check, found %d "
                    "(the app changed; re-derive the snippet from the new file)"
                    % (path, count)
                )
        if REQUEST_HEADER_MARKER not in new_body:
            new_body, count = REQUEST_HEADER_RE.subn(
                request_header_replacement, new_body
            )
            if count != 1:
                sys.exit(
                    "could not patch %s: expected 1 request-header check, found %d "
                    "(the app changed; re-derive the snippet from the new file)"
                    % (path, count)
                )
        if POLICY_MARKER not in new_body:
            new_body, count = POLICY_RE.subn(policy_replacement, new_body)
            if count != 1:
                sys.exit(
                    "could not patch %s: expected 1 origin-policy check, found %d "
                    "(the app changed; re-derive the snippet from the new file)"
                    % (path, count)
                )
        tmp = path + ".tmp-patch"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(new_body)
        shutil.copymode(path, tmp)
        os.replace(tmp, path)
        print("patched browser-service gates: %s" % path)

    if node_repl_status() == "patched":
        print("already patched: %s" % NODE_REPL)
    else:
        if not is_text_file(NODE_REPL):
            shutil.copy2(NODE_REPL, NODE_REPL_VENDOR)
            print("kept vendor binary -> %s" % NODE_REPL_VENDOR)
        elif not os.path.exists(NODE_REPL_VENDOR):
            sys.exit(
                "node_repl is a wrapper but %s is missing; restore or reinstall "
                "the app before applying" % NODE_REPL_VENDOR
            )
        with open(NODE_REPL, "w") as fh:
            fh.write(WRAPPER)
        os.chmod(NODE_REPL, 0o755)
        print("patched gate 1: %s -> %s" % (NODE_REPL, SHIM))
    return check()


def restore():
    for path, backup in mjs_targets():
        if os.path.exists(backup):
            shutil.copy2(backup, path)
            print("restored %s" % path)
        else:
            print("no backup for %s; left as is" % path)
    if os.path.exists(NODE_REPL_VENDOR):
        try:
            os.chmod(NODE_REPL, 0o755)
        except OSError:
            pass
        os.remove(NODE_REPL)
        os.rename(NODE_REPL_VENDOR, NODE_REPL)
        print("restored vendor node_repl")
    print("restored; relaunch the app to load the unpatched bundle")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="report patch state (default)")
    group.add_argument("--apply", action="store_true", help="back up and patch")
    group.add_argument("--restore", action="store_true", help="put the originals back")
    args = parser.parse_args()
    if args.apply:
        sys.exit(apply_patch())
    if args.restore:
        sys.exit(restore())
    sys.exit(check())


if __name__ == "__main__":
    main()
